config/routes.rb
  
Rails.application.routes.draw do
  resources :posts
 scope module: :public do
   devise_for :admin, skip: [:registrations, :password], controllers: {
     sessions: 'admin/sessions'
   }
   devise_for :users
   get "search" => "searches#search"
   resources :reviews do
     resources :comments, only: [:create]
   end
   root to: "homes#top"
   get 'homes/about', to: 'homes#about',as:'about'
   resources :users
  end
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
    resources :comments, only: [:index,:destroy]
    resources :groups, only: [:new, :index, :show, :create, :edit, :update]
  end

end
 

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
   has_one_attached :image
   belongs_to :user
   belongs_to :review
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users, dependent: :destroy
  

  validates :name, presence: true
  validates :introduction, presence: true
  

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
   has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
   has_one_attached :image
    has_many :comments, dependent: :destroy
   belongs_to :user
   belongs_to :category
   # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @review = Review.where("product_name LIKE?","#{word}")
    elsif search == "forward_match"
      @review= Review.where("product_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @review = Review.where("product_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @review = Review.where("product_name LIKE?","%#{word}%")
    else
      @review = Review.all
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
   has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
          has_many :reviews, dependent: :destroy
          
          has_many :comments, dependent: :destroy
          has_one_attached :profile_image
            has_many :group_users, dependent: :destroy
            
            def get_group_image
               (group_image.attached?) ? group_image : 'no_image.jpg'
            end

  
          # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
  
  # 画像のリサイズ処理などを行い、指定したサイズのイメージを返す
  end
end
 

app/controllers/admin/groups_controller.rb
class Admin::GroupsController < ApplicationController
 before_action :authenticate_user! 
  before_action :ensure_correct_user, only: [:edit, :update]
   def index
    @review = Review.new
    @groups = Group.all
    @user = User.find(current_user.id)
   end

  def show
    @review = Review.new
    @group = Group.find(params[:id])
    @user = User.find(current_user.id)
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.owner_id = current_user.id
    if @group.save
      redirect_to groups_path
    else
      render :new
    end
  end

  def edit
    @group = Group.find(params[:id])
  end

  def update
    if @group.update(group_params)
      redirect_to groups_path
    else
      render :edit
    end
  end

  private

    def group_params
      params.require(:group).permit(:name, :introduction, :group_image)
    end

    def ensure_correct_user
      @group = Group.find(params[:id])
      unless @group.owner_id == current_user.id
        redirect_to groups_path
      end
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
   @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :title, tag_ids: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
     @user=current_user
    @reviews=Review.all
    @users=User.all
    
  end
 def show
  @user = User.find(params[:id])
  @reviews = @user.reviews
 end
  def edit
    @user = User.find(params[:id])
  end
   
  def create
    @user = User.new
    @user.user_id = current_user.id
   if  @user.save
       flash[:notice] = " Welcome! You have signed up successfully."
    redirect_to user_path
   else  flash[:notice] = " Signed in successfully. "
    redirect_to user_path


   end
  end

  def update
    @user = User.find(params[:id])
    @user.update(user_params)
   if  @user.save
       flash[:notice] = "You have updated user successfully."
       redirect_to user_path(@user)
   else
       render :edit
   end
  end
  
  

  

 private

 def user_params
  params.require(:user).permit(:name, :introduction, :profile_image)
 end
 def is_matching_login_user
    user = User.find(params[:id])
    unless user.id == current_user.id
      redirect_to user_path(current_user)
    end
 end
end 
   

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/groups/_form.html.erb
<%= form_with model: @group, local: true do |f| %>

  <div class="form-group">
    <%= f.label :グループ名 %>
    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :紹介文 %>
    <%= f.text_area :introduction, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :グループ画像 %>
    <%= f.file_field :group_image, class: "form-control-file", accept: "image/*" %>
  </div>

  <div class="form-group">
    <%= f.submit class: "btn btn-info" %>
  </div>

<% end %>

app/views/admin/groups/_index.html.erb
<table class="table">
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% groups.each do |group| %>
    <tr>
      <td><%= image_tag group.get_group_image, size: "50x50" %></td>
      <td><%= link_to group.name, group_path(group) %></td>
      <td><%= link_to "Show", group, class: "group_#{group.id}" %></td>
      <% if group.is_owned_by?(current_user) %>
        <td><%= link_to "Edit", edit_group_path(group), class: "btn btn-success group_#{group.id}" %></td>
      <% end %>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/admin/groups/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h2>Editing Group</h2>
      <%= render 'layouts/errors', obj: @group %>
      <%= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/admin/groups/index.html.erb
<div class="container px-5 px-sm-0">
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%#= render partial: "users/info", locals: { user: @user }%>

      <h2>New Review</h2>
      <div class="mt-3">
      <%#= render partial: "reviews/form", locals: { review: @review } %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Groups</h2>
      <%= render 'index', groups: @groups %>
    </div>

  </div>
</div>
</div>

app/views/admin/groups/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
      <h3>New Group</h3>
      <%#= render 'layouts/errors', obj: @group %>
      <%#= render 'form', group: @group %>
    </div>
  </div>
</div>

app/views/admin/groups/show.html.erb
<div class="container px-5 px-sm-0">
  <%= render 'layouts/errors', obj: @review %>
  <div class="row">

    <div class="col-md-3">
      <h2>User info</h2>
      <%= render partial: "users/info", locals: { user: @user }%>

      <h2 class="mt-3">New Book</h2>
      <%= render partial: "reviews/form", locals: { review: @review } %>
    </div>

    <div class="col-md-8 offset-md-1">
      <h2>Group Detail</h2>
      <table class="table table-hover table-inverse">
        <thead>
          <tr>
            <th></th>
            <th>グループ名</th>
            <th>紹介文</th>
            <th colspan="3"></th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><%= image_tag @group.get_group_image, size: "50x50" %></td>
            <td><%= @group.name %></td>
            <td><%= @group.introduction %></td>
            <td>
              <% if @group.owner_id == current_user.id %>
                <%= link_to "Edit", edit_group_path(@group), class: "btn btn-success" %>
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>

  </div>
</div>