config/routes.rb
  
Rails.application.routes.draw do
  resources :posts
 scope module: :public do
   devise_for :admin, skip: [:registrations, :password], controllers: {
     sessions: 'admin/sessions'
   }
   devise_for :users
   get "search" => "searches#search"
   resources :reviews do
     resources :comments, only: [:create]
   end
   root to: "homes#top"
   get 'homes/about', to: 'homes#about',as:'about'
   resources :users
  end
  namespace :admin do
    get 'dashboards', to: 'dashboards#index'
    resources :users, only: [:destroy]
    resources :comments, only: [:index,:destroy]
    resources :groups, only: [:new, :index, :show, :create, :edit, :update]
  end

end
 

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/comment.rb
class Comment < ApplicationRecord
   has_one_attached :image
   belongs_to :user
   belongs_to :review
end

app/models/group.rb
class Group < ApplicationRecord
    has_many :group_users, dependent: :destroy
  

  validates :name, presence: true
  validates :introduction, presence: true
  

end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/models/post.rb
class Post < ApplicationRecord
   has_many :post_tags, dependent: :destroy
    has_many :tags, through: :post_tags
end

app/models/post_tag.rb
class PostTag < ApplicationRecord
  belongs_to :post
  belongs_to :tag
end

app/models/review.rb
class Review < ApplicationRecord
   has_one_attached :image
    has_many :comments, dependent: :destroy
   belongs_to :user
   belongs_to :category
   # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @review = Review.where("product_name LIKE?","#{word}")
    elsif search == "forward_match"
      @review= Review.where("product_name LIKE?","#{word}%")
    elsif search == "backward_match"
      @review = Review.where("product_name LIKE?","%#{word}")
    elsif search == "partial_match"
      @review = Review.where("product_name LIKE?","%#{word}%")
    else
      @review = Review.all
    end
  end

end

app/models/tag.rb
class Tag < ApplicationRecord
   has_many :post_tags, dependent: :destroy
    has_many :posts, through: :post_tags
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
          has_many :reviews, dependent: :destroy
          
          has_many :comments, dependent: :destroy
          has_one_attached :profile_image
            has_many :group_users, dependent: :destroy
            
            def get_group_image
               (group_image.attached?) ? group_image : 'no_image.jpg'
            end

  
          # 検索方法分岐
  def self.looks(search, word)
    if search == "perfect_match"
      @user = User.where("name LIKE?", "#{word}")
    elsif search == "forward_match"
      @user = User.where("name LIKE?","#{word}%")
    elsif search == "backward_match"
      @user = User.where("name LIKE?","%#{word}")
    elsif search == "partial_match"
      @user = User.where("name LIKE?","%#{word}%")
    else
      @user = User.all
    end
  end

  def get_profile_image(width, height)
   unless profile_image.attached?
    file_path = Rails.root.join('app/assets/images/sample-author1.jpg')
    profile_image.attach(io: File.open(file_path), filename: 'default-image.jpg', content_type: 'image/jpeg')
   end
  
  # 画像のリサイズ処理などを行い、指定したサイズのイメージを返す
  end
end
 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
   @posts = params[:tag_id].present? ? Tag.find(params[:tag_id]).posts : Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to post_url(@post), notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:body, :title, tag_ids: [])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def index
    @user=current_user
    @reviews=Review.all
   @review=Review.new
  end
  
  

  def new
    @review=Review.new
   
  end

   
  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    if @review.save
      flash[:notice] = "You have created review successfully."
      redirect_to review_path(@review)
    else
      @user = current_user
      @reviews = Review.all
      render :index
    end

  end



  def edit
      @review = Review.find(params[:id])
    
  end
    

  def update

    @review = Review.find(params[:id])
    @review.update(review_params)
     if  @review.save
         flash[:notice] = "You have updated review successfully.."
    redirect_to review_path
     else
      @user=current_user
     @reviews=Review.all
    render :edit
     end
  end

 def show

      @reviews=Review.all
      @review=Review.find(params[:id])
       @user=@review.user
 end
 
   def destroy
    review = Review.find(params[:id])
    review.destroy
    redirect_to reviews_path

   end
  private

  def review_params
     params.require(:review).permit(:product_name, :amount, :category_id, :rate)
  end
   def is_matching_login_user
   review = Review.find(params[:id])
    unless review.user_id == current_user.id
      redirect_to reviews_path
    end
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comment_helper.rb
module CommentHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_form.erb
 <h1>New review</h1>
<%= form_with model: Review.new do |f| %>

  <h4>商品名</h4>
  <%= f.text_field :product_name %>
  <h4>金額</h4>
  <%= f.number_field :amount %>
  <h2>カテゴリー</h2>
  <%= f.collection_select :category_id, Category.all, :id, :brand_name, { prompt: '選択してください' }, class: 'form-control' %>


  <% if review.id.nil? %>
    <div class="form-group" id="rate">
      <%= f.label :rate %>
      <%= f.hidden_field :rate, id: :review_star, class: 'form-control' %>
      <div id="post_raty"></div>
    </div>
    <script>
      $(document).on('turbolinks:load', function() {
        let elem = document.querySelector('#post_raty');
        if (elem == null) return;
        elem.innerHTML = "";
        let opt = {
          starOn: "<%= asset_path('star-on.png') %>",
          starOff: "<%= asset_path('star-off.png') %>",
          starHalf: "<%= asset_path('star-half.png') %>",
          scoreName: 'review[rate]',
          half: true
        };
        raty(elem, opt);
      });
    </script>

    <%= f.submit 'Create Review' %>


  <% else %>
    <div class="form-group">
       # 評価の編集機能実装時に考える
      <%= render "review", review: @review %>
    </div>
  <% end %>


<% end %>

app/views/reviews/_static_rate.html.erb
<div id="star_<%= review.id %>"></div>
<script>
$(document).on('turbolinks:load', function() {
  let elem = document.querySelector('#star_<%= review.id %>');
  if (elem == null) return;
  
  elem.innerHTML = "";
  let opt = {  
    starOn: "<%= asset_path('star-on.png') %>",
    starOff: "<%= asset_path('star-off.png') %>",
    starHalf: "<%= asset_path('star-half.png') %>",
    score: "<%= review.rate %>",
    readOnly: true,
  };
  raty(elem, opt);
});
</script>

app/views/reviews/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
<h2>Editing Review</h2>
<% if @review.errors.any? %>
  <%= @review.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
<%= form_with model: @review do |f| %>
 <h4>商品名</h4>
  <%= f.text_field :product_name %>
  <h4>金額</h4>
  <%= f.number_field :amount %>
  <h2>カテゴリー</h2>
  <%= f.collection_select :category_id, Category.all, :id, :brand_name, { prompt: '選択してください' }, class: 'form-control' %>
  
 
<br>
  <%= f.submit 'Update Review',class: "btn btn-secondary" %>
<br>
  <%= link_to "Show", review_path(@review) %> | <%= link_to "Back", reviews_path %>
   

<% end %>
</div>
</div>
</div>

app/views/reviews/index.html.erb
<% if @review.errors.any? %>
  <%= @review.errors.count %>errors prohibited this obj from being saved:
  <ul>
    <% @review.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>
  <div class="container">
  <div class="row">
    <div class="col-md-3">


</div>
<div class="col-md-8 offset-md-1">
  <h2>reviews</h2>

  <table class="table table-hover table-inverse">
    
  <thead>
      <th>商品名</th>
      <th>金額</th>
      <th>ブランド名</th>
      <th colspan="3"></th>
  </thead>
<tbody>
  <% @reviews.each do |review| %>
  <tr>
   <%#= link_to image_tag(@user.get_profile_image(100, 100)), review.user %>
  
<%#= link_to review.product_name, review_path(review.id)%> 
  <td><%= link_to review.product_name, review_path(review.id)%> </td>
  <td><%=review.amount  %></td>
　<td><%=review.category.brand_name%></td>
   <td> <%= link_to "Edit", edit_review_path(review.id) %></td>
   <td> <%= link_to "Destroy", review_path(review.id), method: :delete, "data-confirm" => "本当に消しますか？" %></td>
<% end %>
</tr>
</tbody>
</table>
 
 <%=link_to "投稿フォームへ",new_review_path%>
</div>
</div>
</div>

app/views/reviews/new.html.erb
  <h1>投稿フォーム</h1>
  


  
  <%= render 'form', review: Review.new %>


  